package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"pdfprase/util"
	"strconv"
	"strings"
)
type Blog struct {
	ID      int
	Author   struct {
		Name  string
		Email string
	}`gorm:"embedded"`
	Upvotes int32
}
var tableName string
var mapStruct map[string]bool
type AutoGenerated struct {
	BusinessPatentDocumentAndRelated struct {
		XmlnsBase                 string `json:"-xmlns:base" gorm:"text"`
		XmlnsBusiness             string `json:"-xmlns:business" gorm:"text"`
		XmlnsM                    string `json:"-xmlns:m" gorm:"text"`
		XmlnsTbl                  string `json:"-xmlns:tbl" gorm:"text"`
		XmlnsXsi                  string `json:"-xmlns:xsi"`
		XsiSchemaLocation         string `json:"-xsi:schemaLocation"`
		XsdVersion                string `json:"-xsdVersion"`
		File                      string `json:"-file"`
		DateProduced              string `json:"-dateProduced"`
		Status                    string `json:"-status"`
		Lang                      string `json:"-lang"`
		Country                   string `json:"-country"`
		DocNumber                 string `json:"-docNumber"`
		Kind                      string `json:"-kind"`
		DatePublication           string `json:"-datePublication"`
		BusinessBibliographicData struct {
			BusinessPublicationReference []struct {
				DataFormat     string `json:"-dataFormat"`
				Sequence       string `json:"-sequence"`
				SourceDB       string `json:"-sourceDB,omitempty"`
				BaseDocumentID struct {
					BaseWIPOST3Code string `json:"base:WIPOST3Code"`
					BaseDocNumber   string `json:"base:DocNumber"`
					BaseKind        string `json:"base:Kind"`
					BaseDate        string `json:"base:Date"`
				} `json:"base:DocumentID" gorm:"embedded"`
			} `json:"business:PublicationReference"gorm:"embedded"`
			BusinessPublicAvailabilityDate struct {
				BusinessGazetteReference struct {
					BusinessGazetteNumber string `json:"business:GazetteNumber"`
					BaseDate              string `json:"base:Date"`
				} `json:"business:GazetteReference"gorm:"embedded"`
			} `json:"business:PublicAvailabilityDate"gorm:"embedded"`
			BusinessApplicationReference []struct {
				ApplType       string `json:"-applType"`
				DataFormat     string `json:"-dataFormat"`
				Sequence       string `json:"-sequence"`
				SourceDB       string `json:"-sourceDB,omitempty"`
				BaseDocumentID struct {
					BaseWIPOST3Code string `json:"base:WIPOST3Code"`
					BaseDocNumber   string `json:"base:DocNumber"`
					BaseDate        string `json:"base:Date"`
				} `json:"base:DocumentID"gorm:"embedded"`
			} `json:"business:ApplicationReference"gorm:"embedded"`
			BusinessClassificationIPCRDetails struct {
				Creator                    string `json:"-creator"`
				ProcessingType             string `json:"-processingType"`
				BusinessClassificationIPCR []struct {
					Sequence                 string `json:"-sequence"`
					BusinessIPCVersionDate   string `json:"business:IPCVersionDate"`
					BusinessSection          string `json:"business:Section"`
					BusinessMainClass        string `json:"business:MainClass"`
					BusinessSubclass         string `json:"business:Subclass"`
					BusinessMainGroup        string `json:"business:MainGroup"`
					BusinessSubgroup         string `json:"business:Subgroup"`
					BusinessGeneratingOffice struct {
						BaseWIPOST3Code string `json:"base:WIPOST3Code"`
					} `json:"business:GeneratingOffice"gorm:"embedded"`
					BusinessClassificationDataSource string `json:"business:ClassificationDataSource"`
					BaseText                         string `json:"base:Text"`
				} `json:"business:ClassificationIPCR"gorm:"embedded"`
			} `json:"business:ClassificationIPCRDetails"gorm:"embedded"`
			BusinessInventionTitle struct {
				Lang           string `json:"-lang"`
				DataFormat     string `json:"-dataFormat"`
				SourceDB       string `json:"-sourceDB"`
				ProcessingType string `json:"-processingType"`
				Creator        string `json:"-creator"`
				Text           string `json:"#text"`
			} `json:"business:InventionTitle"gorm:"embedded"`
			BusinessReferencesCited struct {
				SourceDB         string `json:"-sourceDB"`
				BusinessCitation []struct {
					SrepPhase                   string `json:"-srepPhase"`
					Sequence                    string `json:"-sequence"`
					BusinessApplicationCitation struct {
						ID                           string `json:"-id"`
						Num                          string `json:"-num"`
						BusinessPublicationReference []struct {
							DataFormat     string `json:"-dataFormat"`
							Sequence       string `json:"-sequence"`
							BaseDocumentID struct {
								BaseWIPOST3Code string `json:"base:WIPOST3Code"`
								BaseDocNumber   string `json:"base:DocNumber"`
								BaseKind        string `json:"base:Kind"`
								BaseDate        string `json:"base:Date"`
							} `json:"base:DocumentID"gorm:"embedded"`
							SourceDB string `json:"-sourceDB,omitempty"`
						} `json:"business:PublicationReference"gorm:"embedded"`
					} `json:"business:ApplicationCitation"gorm:"embedded"`
					BusinessNPLCitation struct {
						ID       string `json:"-id"`
						Num      string `json:"-num"`
						BaseText string `json:"base:Text"`
					} `json:"business:NPLCitation,omitempty"gorm:"embedded"`
				} `json:"business:Citation"gorm:"embedded"`
			} `json:"business:ReferencesCited"gorm:"embedded"`
			BusinessRelatedDocuments struct {
				BusinessRelatedPublicationDoc struct {
					BaseDocumentID struct {
						Sequence        string `json:"-sequence"`
						BaseWIPOST3Code string `json:"base:WIPOST3Code"`
						BaseDocNumber   string `json:"base:DocNumber"`
						BaseKind        string `json:"base:Kind"`
						BaseDate        string `json:"base:Date"`
					} `json:"base:DocumentID"gorm:"embedded"`
				} `json:"business:RelatedPublicationDoc"gorm:"embedded"`
			} `json:"business:RelatedDocuments"gorm:"embedded"`
			BusinessParties struct {
				BusinessApplicantDetails struct {
					Representative    string `json:"-representative"`
					BusinessApplicant struct {
						Sequence        string `json:"-sequence"`
						AppType         string `json:"-appType"`
						DataFormat      string `json:"-dataFormat"`
						SourceDB        string `json:"-sourceDB"`
						Lang            string `json:"-lang"`
						Creator         string `json:"-creator"`
						ProcessingType  string `json:"-processingType"`
						BaseAddressBook struct {
							Lang        string `json:"-lang"`
							BaseName    string `json:"base:Name"`
							BaseAddress struct {
								BaseAddressLine     string `json:"base:AddressLine"`
								BaseAddressMailCode string `json:"base:AddressMailCode"`
								BasePostBox         string `json:"base:PostBox"`
								BaseAddressRoom     string `json:"base:AddressRoom"`
								BaseAddressFloor    string `json:"base:AddressFloor"`
								BaseAddressBuilding string `json:"base:AddressBuilding"`
								BaseStreet          string `json:"base:Street"`
								BaseAddressCity     string `json:"base:AddressCity"`
								BaseCounty          string `json:"base:County"`
								BaseCity            string `json:"base:City"`
								BaseProvince        string `json:"base:Province"`
								BasePostCode        string `json:"base:PostCode"`
								BaseWIPOST3Code     string `json:"base:WIPOST3Code"`
								BaseText            string `json:"base:Text"`
							} `json:"base:Address"gorm:"embedded"`
						} `json:"base:AddressBook"gorm:"embedded"`
						BusinessOrganizationCode struct {
							CreateDate string `json:"-createDate"`
							Creator    string `json:"-creator"`
							Text       string `json:"#text"`
						} `json:"business:OrganizationCode"gorm:"embedded"`
					} `json:"business:Applicant"gorm:"embedded"`
				} `json:"business:ApplicantDetails"gorm:"embedded"`
				BusinessInventorDetails struct {
					BusinessInventor []struct {
						Sequence        string `json:"-sequence"`
						DataFormat      string `json:"-dataFormat"`
						SourceDB        string `json:"-sourceDB"`
						Lang            string `json:"-lang"`
						PublicationMark string `json:"-publicationMark"`
						Creator         string `json:"-creator"`
						ProcessingType  string `json:"-processingType"`
						BaseAddressBook struct {
							Lang     string `json:"-lang"`
							BaseName string `json:"base:Name"`
						} `json:"base:AddressBook"gorm:"embedded"`
					} `json:"business:Inventor"gorm:"embedded"`
				} `json:"business:InventorDetails"gorm:"embedded"`
				BusinessAgentDetails struct {
					BusinessCustomerNumber string `json:"business:CustomerNumber"`
					BusinessAgent          []struct {
						Sequence       string `json:"-sequence"`
						Lang           string `json:"-lang"`
						DataFormat     string `json:"-dataFormat"`
						SourceDB       string `json:"-sourceDB"`
						RepType        string `json:"-repType"`
						ProcessingType string `json:"-processingType"`
						Creator        string `json:"-creator"`
						BusinessAgency struct {
							BaseAddressBook struct {
								Lang                 string `json:"-lang"`
								BaseOrganizationName string `json:"base:OrganizationName"`
							} `json:"base:AddressBook"gorm:"embedded"`
						} `json:"business:Agency"gorm:"embedded"`
						BaseAddressBook struct {
							Lang     string `json:"-lang"`
							BaseName string `json:"base:Name"`
						} `json:"base:AddressBook"gorm:"embedded"`
					} `json:"business:Agent"gorm:"embedded"`
				} `json:"business:AgentDetails"gorm:"embedded"`
			} `json:"business:Parties"gorm:"embedded"`
			BusinessAssigneeDetails struct {
				BusinessAssignee struct {
					Sequence        string `json:"-sequence"`
					DataFormat      string `json:"-dataFormat"`
					SourceDB        string `json:"-sourceDB"`
					Lang            string `json:"-lang"`
					Creator         string `json:"-creator"`
					BaseAddressBook struct {
						Lang        string `json:"-lang"`
						BaseName    string `json:"base:Name"`
						BaseAddress struct {
							BaseAddressLine     string `json:"base:AddressLine"`
							BaseAddressMailCode string `json:"base:AddressMailCode"`
							BasePostBox         string `json:"base:PostBox"`
							BaseAddressRoom     string `json:"base:AddressRoom"`
							BaseAddressFloor    string `json:"base:AddressFloor"`
							BaseAddressBuilding string `json:"base:AddressBuilding"`
							BaseStreet          string `json:"base:Street"`
							BaseAddressCity     string `json:"base:AddressCity"`
							BaseCounty          string `json:"base:County"`
							BaseCity            string `json:"base:City"`
							BaseProvince        string `json:"base:Province"`
							BasePostCode        string `json:"base:PostCode"`
							BaseWIPOST3Code     string `json:"base:WIPOST3Code"`
							BaseText            string `json:"base:Text"`
						} `json:"base:Address"gorm:"embedded"`
					} `json:"base:AddressBook"gorm:"embedded"`
					BusinessAssigneeCode string `json:"business:AssigneeCode"gorm:"embedded"`
				} `json:"business:Assignee"gorm:"embedded"`
			} `json:"business:AssigneeDetails"gorm:"embedded"`
			BusinessExaminerDetails struct {
				BusinessExaminer struct {
					Sequence string `json:"-sequence"`
					Lang     string `json:"-lang"`
					Creator  string `json:"-creator"`
					BaseName string `json:"base:Name"`
				} `json:"business:Examiner"gorm:"embedded"`
			} `json:"business:ExaminerDetails"gorm:"embedded"`
		} `json:"business:BibliographicData"gorm:"embedded"`
		BusinessAbstract struct {
			DataFormat     string `json:"-dataFormat"`
			Lang           string `json:"-lang"`
			SourceDB       string `json:"-sourceDB"`
			ProcessingType string `json:"-processingType"`
			Creator        string `json:"-creator"`
			BaseParagraphs struct {
				Num  string `json:"-num"`
				Text string `json:"#text"`
			} `json:"base:Paragraphs"gorm:"embedded"`
			BusinessAbstractFigure struct {
				BaseFigure struct {
					Num       string `json:"-num"`
					BaseImage struct {
						He         string `json:"-he"`
						Wi         string `json:"-wi"`
						File       string `json:"-file"`
						ImgContent string `json:"-imgContent"`
						ImgFormat  string `json:"-imgFormat"`
					} `json:"base:Image"gorm:"embedded"`
				} `json:"base:Figure"gorm:"embedded"`
			} `json:"business:AbstractFigure"gorm:"embedded"`
		} `json:"business:Abstract"gorm:"embedded"`
		BusinessDescription struct {
			Lang                   string `json:"-lang"`
			DataFormat             string `json:"-dataFormat"`
			SourceDB               string `json:"-sourceDB"`
			Creator                string `json:"-creator"`
			BusinessInventionTitle struct {
				ID   string `json:"-id"`
				Text string `json:"#text"`
			} `json:"business:InventionTitle"gorm:"embedded"`
			BusinessTechnicalField struct {
				ID             string `json:"-id"`
				BaseParagraphs []struct {
					ID   string `json:"-id"`
					Text string `json:"#text"`
					Num  string `json:"-num,omitempty"`
				} `json:"base:Paragraphs"gorm:"embedded"`
			} `json:"business:TechnicalField"gorm:"embedded"`
			BusinessBackgroundArt struct {
				ID             string `json:"-id"`
				BaseParagraphs []struct {
					ID   string `json:"-id"`
					Text string `json:"#text"`
					Num  string `json:"-num,omitempty"`
				} `json:"base:Paragraphs"gorm:"embedded"`
			} `json:"business:BackgroundArt"gorm:"embedded"`
			BusinessDisclosure struct {
				ID             string `json:"-id"`
				BaseParagraphs []struct {
					ID   string `json:"-id"`
					Text string `json:"#text"`
					Num  string `json:"-num,omitempty"`
				} `json:"base:Paragraphs"gorm:"embedded"`
			} `json:"business:Disclosure"gorm:"embedded"`
			BusinessDrawingsDescription struct {
				ID             string `json:"-id"`
				BaseParagraphs []struct {
					ID   string `json:"-id"`
					Text string `json:"#text"`
					Num  string `json:"-num,omitempty"`
				} `json:"base:Paragraphs"gorm:"embedded"`
			} `json:"business:DrawingsDescription"gorm:"embedded"`
			BusinessInventionMode struct {
				ID             string `json:"-id"`
				BaseParagraphs []struct {
					ID   string `json:"-id"`
					Text string `json:"#text"`
					Num  string `json:"-num,omitempty"`
					BaseSub          string `json:"base:Sub,omitempty"`
					BaseTableDetails struct {
						Num       string `json:"-num"`
						BaseTable struct {
							TblTgroup struct {
								Cols       string `json:"-cols"`
								TblColspec []struct {
									Colname  string `json:"-colname"`
									Colwidth string `json:"-colwidth"`
								} `json:"tbl:colspec"`
								TblTbody struct {
									TblRow []struct {
										TblEntry []struct {
											Morerows string `json:"-morerows"`
											Text     string `json:"#text"`
										} `json:"tbl:entry"gorm:"embedded"`
									} `json:"tbl:row"gorm:"embedded"`
								} `json:"tbl:tbody"gorm:"embedded"`
							} `json:"tbl:tgroup"gorm:"embedded"`
						} `json:"base:Table"gorm:"embedded"`
					} `json:"base:TableDetails,omitempty"gorm:"embedded"`
				} `json:"base:Paragraphs"gorm:"embedded"`
			} `json:"business:InventionMode"gorm:"embedded"`
		} `json:"business:Description"gorm:"embedded"`
		BusinessDrawings struct {
			Lang       string `json:"-lang"`
			SourceDB   string `json:"-sourceDB"`
			BaseFigure []struct {
				ID           string `json:"-id"`
				Num          string `json:"-num"`
				FigureLabels string `json:"-figureLabels"`
				BaseImage    struct {
					ID          string `json:"-id"`
					He          string `json:"-he"`
					Wi          string `json:"-wi"`
					File        string `json:"-file"`
					ImgContent  string `json:"-imgContent"`
					ImgFormat   string `json:"-imgFormat"`
					Orientation string `json:"-orientation"`
					Inline      string `json:"-inline"`
				} `json:"base:Image"gorm:"embedded"`
			} `json:"base:Figure"gorm:"embedded"`
		} `json:"business:Drawings"gorm:"embedded"`
		BusinessClaims struct {
			Lang          string `json:"-lang"`
			DataFormat    string `json:"-dataFormat"`
			SourceDB      string `json:"-sourceDB"`
			Creator       string `json:"-creator"`
			BusinessClaim []struct {
				ID                string   `json:"-id"`
				Num               string   `json:"-num"`
				BusinessClaimText []string `json:"business:ClaimText"`
			} `json:"business:Claim"gorm:"embedded"`
		} `json:"business:Claims"gorm:"embedded"`
	} `json:"business:PatentDocumentAndRelated"gorm:"embedded"`
}
func GetPdfList(root string)([]string,error){//获取当前文件夹下面的列表，返回的是路径
	files, err := ioutil.ReadDir(root)
	if err != nil {
		return nil,err
	}
	filesName:=make([]string,0)
	for _, file := range files {
		if file.Name()=="end.txt"{
			continue
		}
		filesName=append(filesName,root+"/"+file.Name())
	}
	return filesName,nil
}
func getJSON(root string)(string,error){//获取切割后的pdf文件内容
	fileTxt, err := ioutil.ReadFile(root)
	if err!=nil{
		return "",err
	}
	return string(fileTxt),nil
}
func Test_RunXml() {
	fileList,err:=GetPdfList("./xmlresource/jsondir")
	if err!=nil{
		return
	}
	mapStruct=make(map[string]bool)
	err=util.InitDB("user","psw","db")
	if err!=nil{
		err.Error()
		return
	}
	tableName="testxml"
	sqlCreateTable:="CREATE TABLE "+tableName+" ( `ID` INT NOT NULL AUTO_INCREMENT,"
	sqlCreateTable+="PRIMARY KEY(`ID`));"
	err= util.DB.Exec(sqlCreateTable).Error
	if err!=nil {
		fmt.Println(err.Error())
		return
	}
	for k:=1;k<len(fileList)+1;k++{
		strdata,err:=getJSON(fileList[k-1])
		if err!=nil {
			return
		}
		jsonStr := []byte(strdata)    //获取json数据将其转换成byte数组
		//jsonStr := []byte(`[{"data":[{"a":"aa","b":null},{"c":[1,2,2]},{"list":["dd","1","ff"]}]}]`)


		sqlInit:="INSERT INTO "+tableName+" (ID) VALUES ( "+strconv.Itoa(k)+" );"
		err= util.DB.Exec(sqlInit).Error
		if err!=nil {
			fmt.Println(err.Error())
			return
		}
			//在这里读取文件
			if (strings.Index(string(jsonStr[:]), "[") == 0) {
				var f []interface{}
				err := json.Unmarshal(jsonStr, &f)
				if err != nil {
					fmt.Println(err)
				}
				jsonArrayParse(f,"array",k)
			} else {
				var f interface{}
				err := json.Unmarshal(jsonStr, &f)
				if err != nil {
					fmt.Println(err)
				}
				jsonObjectParse(f,"",k)
			}

	}
}
func jsonArrayParse(vv []interface{},tag string,id int){
	for i, u := range vv {
		switch vv1 := u.(type) {
		case string:
			strData:=tag+strconv.Itoa(i)
			if strings.Contains(strData,"@id"){
				continue
			}
			if strings.Contains(strData,"@num"){
				continue
			}
			if len(vv1)==1{
				continue
			}
			strData=strings.Replace(strData, "business:", "", -1)
			strData=strings.Replace(strData, "PatentDocumentAndRelated", "XML", -1)
			if len(strData)>64{
				strData=strData[len(strData)-64:]
			}
			if len(mapStruct)>=4096{
				fmt.Println("表列太多")
				continue
			}
			if mapStruct[strData]==false{
				sqlAlter:="ALTER TABLE "+tableName+" ADD "+"`"+strData+"`"+" TEXT;"
				err:=util.DB.Exec(sqlAlter).Error
				if err!=nil {
					fmt.Println(err.Error())
					return
				}
				mapStruct[strData]=true
			}

			sqlInsert:="UPDATE "+tableName+" SET `"+strData+"` = "+" '"+vv1+"' "+"WHERE ID = "+strconv.Itoa(id)+";"
			fmt.Println(sqlInsert)
			err:=util.DB.Exec(sqlInsert).Error
			if err!=nil {
				fmt.Println(err.Error())
				return
			}
			fmt.Println(strData, "------------[string] :", vv1)
		case float64:
			fmt.Println(tag+strconv.Itoa(i), "[float64]:", u)
		case bool:
			fmt.Println(tag+strconv.Itoa(i), "[bool]:", u)
		case nil:
			fmt.Println(tag+strconv.Itoa(i), "[nil]:", u)
		case []interface{}:
			//fmt.Println(i, "[array_] :", u)
			jsonArrayParse(vv1,tag+strconv.Itoa(i),id)
		case interface{}:
			//fmt.Println(i, "[interface_]:",u)
			m1 := u.(map[string]interface{})
			jsonObjectParse(m1,tag+strconv.Itoa(i),id)
		default:
			fmt.Println("  ", tag+strconv.Itoa(i), "[type?]", u, ", ",vv1)
		}
	}
}

func jsonObjectParse(f interface{},tag string,id int){
	m := f.(map[string]interface{})
	for k, v := range m {
		switch vv := v.(type) {
		case string:
			strData:=tag+k
			if strings.Contains(strData,"@id"){
				continue
			}
			if strings.Contains(strData,"@num"){
				continue
			}
			if len(vv)==1{
				continue
			}
			strData=strings.Replace(strData, "business:", "", -1)
			strData=strings.Replace(strData, "PatentDocumentAndRelated", "XML", -1)
			strData=strings.Replace(strData, ":AddressBookbase:Addressbase:", "", -1)
			if len(strData)>64{
				strData=strData[len(strData)-64:]
			}
			if len(mapStruct)>=4096{
				fmt.Println("表列太多")
				continue
			}
			if mapStruct[strData]==false{
				sqlAlter:="ALTER TABLE "+tableName+" ADD "+"`"+strData+"`"+" TEXT;"
				err:=util.DB.Exec(sqlAlter).Error
				if err!=nil {
					fmt.Println(err.Error())
					return
				}
				mapStruct[strData]=true
			}
			sqlInsert:="UPDATE "+tableName+" SET `"+strData+"` = "+" '"+vv+"' "+"WHERE ID = "+strconv.Itoa(id)+";"
			fmt.Println(sqlInsert)
			err:=util.DB.Exec(sqlInsert).Error
			if err!=nil {
				fmt.Println(err.Error())
				return
			}
			fmt.Println(strData, "[string] :", vv)
		case float64:
			fmt.Println(tag+k, "[float64]:", vv)
		case bool:
			fmt.Println(tag+k, "[bool]:", vv)
		case nil:
			fmt.Println(tag+k, "[nil]:", vv)
		case []interface{}:
			//fmt.Println(k, "[array]:")
			jsonArrayParse(vv,tag+k,id)
		case interface{}:
			//fmt.Println(k, "[interface]:",vv)
			m1 := v.(map[string]interface{})
			jsonObjectParse(m1,tag+k,id)
		default:
			fmt.Println(tag+k, "[type?]",vv)
		}
	}
}
